"""empty message

Revision ID: 07149be917d9
Revises: a91aa14f9f71
Create Date: 2023-01-07 08:39:25.200025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07149be917d9'
down_revision = 'a91aa14f9f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reglament_works', 'interval_mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reglament_works', 'interval_mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
