"""empty message

Revision ID: 5b29763905b3
Revises: bb96a39e0080
Create Date: 2023-01-07 09:04:44.232070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b29763905b3'
down_revision = 'bb96a39e0080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_model', sa.Column('car_manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint('car_model_manufacturer_id_fkey', 'car_model', type_='foreignkey')
    op.create_foreign_key(None, 'car_model', 'car_manufacturer', ['car_manufacturer_id'], ['id'])
    op.drop_column('car_model', 'manufacturer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_model', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'car_model', type_='foreignkey')
    op.create_foreign_key('car_model_manufacturer_id_fkey', 'car_model', 'car_manufacturer', ['manufacturer_id'], ['id'])
    op.drop_column('car_model', 'car_manufacturer_id')
    # ### end Alembic commands ###
