"""empty message

Revision ID: 68e19d9a1fcb
Revises: 63820e31479c
Create Date: 2023-01-10 09:57:33.513298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e19d9a1fcb'
down_revision = '63820e31479c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_reglament_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_mileage', sa.Integer(), nullable=False),
    sa.Column('interval_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalreglamentxcar',
    sa.Column('car_personal_id', sa.Integer(), nullable=False),
    sa.Column('personal_reglament_work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_personal_id'], ['car_personal.id'], ),
    sa.ForeignKeyConstraint(['personal_reglament_work_id'], ['personal_reglament_works.id'], ),
    sa.PrimaryKeyConstraint('car_personal_id', 'personal_reglament_work_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personalreglamentxcar')
    op.drop_table('personal_reglament_works')
    # ### end Alembic commands ###
