"""empty message

Revision ID: a91aa14f9f71
Revises: d4be53fad00d
Create Date: 2023-01-07 08:36:27.384241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91aa14f9f71'
down_revision = 'd4be53fad00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglament_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_mileage', sa.Integer(), nullable=False),
    sa.Column('interval_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_modification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reglamentxcar',
    sa.Column('car_modification_id', sa.Integer(), nullable=False),
    sa.Column('reglament_work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_modification_id'], ['car_modification.id'], ),
    sa.ForeignKeyConstraint(['reglament_work_id'], ['reglament_works.id'], ),
    sa.PrimaryKeyConstraint('car_modification_id', 'reglament_work_id')
    )
    op.add_column('car_personal', sa.Column('car_modification_id', sa.Integer(), nullable=True))
    op.add_column('car_personal', sa.Column('mileage_date', sa.DateTime(), nullable=True))
    op.add_column('car_personal', sa.Column('mileage', sa.Integer(), nullable=False))
    op.drop_constraint('car_personal_car_model_id_fkey', 'car_personal', type_='foreignkey')
    op.create_foreign_key(None, 'car_personal', 'car_modification', ['car_modification_id'], ['id'])
    op.drop_column('car_personal', 'car_model_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_personal', sa.Column('car_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'car_personal', type_='foreignkey')
    op.create_foreign_key('car_personal_car_model_id_fkey', 'car_personal', 'car_model', ['car_model_id'], ['id'])
    op.drop_column('car_personal', 'mileage')
    op.drop_column('car_personal', 'mileage_date')
    op.drop_column('car_personal', 'car_modification_id')
    op.drop_table('reglamentxcar')
    op.drop_table('car_modification')
    op.drop_table('reglament_works')
    # ### end Alembic commands ###
