"""empty message

Revision ID: bb96a39e0080
Revises: 07149be917d9
Create Date: 2023-01-07 08:39:49.084915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb96a39e0080'
down_revision = '07149be917d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reglament_works', 'interval_mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reglament_works', 'interval_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reglament_works', 'interval_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reglament_works', 'interval_mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
