"""empty message

Revision ID: d4be53fad00d
Revises: 
Create Date: 2023-01-07 07:43:45.961397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4be53fad00d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_manufacturer', 'income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_manufacturer', sa.Column('income', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
